name: thrive_shop
description: Shopping List App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.0.2
  equatable: ^2.0.5
  firebase_core: ^2.1.0
  firebase_products_api:
    path: packages/firebase_products_api
  firebase_storage: ^11.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  formz: ^0.4.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  permission_handler: ^9.0.1
  products_api:
    path: packages/products_api
  products_repository:
    path: packages/products_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
