import 'package:flutter/material.dart';

class AppColors {
  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF773FBF),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFEDDCFF),
    onPrimaryContainer: Color(0xFF290055),
    secondary: Color(0xFF006783),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFBCE9FF),
    onSecondaryContainer: Color(0xFF001F2A),
    tertiary: Color(0xFF7F525A),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD9DF),
    onTertiaryContainer: Color(0xFF321019),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF1D1B1E),
    surface: Color(0xFF773FBF),
    onSurface: Color(0xFFFFFFFF),
    surfaceVariant: Color(0xFFE8E0EB),
    onSurfaceVariant: Color(0xFFE8E0EB),
    outline: Color(0xFF7B757F),
    onInverseSurface: Color(0xFFF5EFF4),
    inverseSurface: Color(0xFF322F33),
    inversePrimary: Color(0xFFD8B9FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF773FBF),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFD8B9FF),
    onPrimary: Color(0xFF450086),
    primaryContainer: Color(0xFF5E21A6),
    onPrimaryContainer: Color(0xFFEDDCFF),
    secondary: Color(0xFF64D3FF),
    onSecondary: Color(0xFF003545),
    secondaryContainer: Color(0xFF004D63),
    onSecondaryContainer: Color(0xFFBCE9FF),
    tertiary: Color(0xFFF2B7C1),
    onTertiary: Color(0xFF4B252D),
    tertiaryContainer: Color(0xFF653B43),
    onTertiaryContainer: Color(0xFFFFD9DF),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF1D1B1E),
    onBackground: Color(0xFFE7E1E5),
    surface: Color(0xFF1D1B1E),
    onSurface: Color(0xFFE7E1E5),
    surfaceVariant: Color(0xFF4A454E),
    onSurfaceVariant: Color(0xFFCCC4CF),
    outline: Color(0xFF958E99),
    onInverseSurface: Color(0xFF1D1B1E),
    inverseSurface: Color(0xFFE7E1E5),
    inversePrimary: Color(0xFF773FBF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFD8B9FF),
  );
}
