// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXUJ5LO-0nZFsuCxxC7HD-HgmEpkYuEnk',
    appId: '1:910876882160:web:b73b687911804303bb7e35',
    messagingSenderId: '910876882160',
    projectId: 'thrive-shop',
    authDomain: 'thrive-shop.firebaseapp.com',
    storageBucket: 'thrive-shop.appspot.com',
    measurementId: 'G-J41V0SS3YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnt-2qLvKuGjVngJFnigYSfPXFcxpYIM',
    appId: '1:910876882160:android:b7621a0099c0f955bb7e35',
    messagingSenderId: '910876882160',
    projectId: 'thrive-shop',
    storageBucket: 'thrive-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2PNdCm6rkMJ2iPPM5iHxQIB6Y1rQW8QI',
    appId: '1:910876882160:ios:32a07c4ba2d57f30bb7e35',
    messagingSenderId: '910876882160',
    projectId: 'thrive-shop',
    storageBucket: 'thrive-shop.appspot.com',
    iosClientId: '910876882160-59ta2l4ndbaqogdmv3s9d089oc34s0jv.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.thrive-shop',
  );
}
