name: firebase_products_api
description: A Flutter implementation of the ProductsApi that uses firebase.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  products_api:
    path: ../products_api

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
